const path = {
  PUBLIC: "/",
  HOMEPAGE: "home",
  ADMIN: "/",
  ADMINDASHBOARD: "",
  HOME: "",
  LOGIN: "sign-in",
  PROFILE: "profile",
  COLLECTION: "",
  CATEGORY_BELT: "/categoryBelt",
  CREATE_CATEGORY_BELT: "/categoryBelt/new",
  DETAILS_CATEGORY_BELT: "/categoryBelt/:id",
  CATEGORY_COLLECTION: "/categoryCollection",
  CREATE_CATEGORY_COLLECTION: "/categoryCollection/new",
  DETAILS_CATEGORY_COLLECTION: "/categoryCollection/:id",
  CUSTOMER: "customers",
  LOTTERY: "lottery",
  INFORMATION: "information",
  NAME: "setName/:id",
  GENDER: "setGender/:id",
  CHANGEPASSWORD: "setPassword/:id",

  BANK: "setBank/:id",
  WITHDRAW: "withdraw/:id",
  HISTORYWITHDRAW: "withdrawalhistory/:id",
  HISTORYWITHDRAWADMIN: "withdrawalhistory",
  HISTORYTRANSFORMADMIN: "withdtransformhistory",

  HISTORYEVALUTE: "evaluatehistory/:id",
  HISTORYEVALUTEADMIN: "evaluatehistory",
  HISTORYDETAILSEVALUTE: "historydetails/:roomId/:userId",
  HISTORYDETAILSEVALUTEADMIN: "historydetails/:roomId",

  HISTORYDEPOSIT: "depositalhistory",
  BELT: "belt",
  SETTING: "setting",
  CREATE_COLLECTION: "collection/new",
  CREATE_LOTTERY: "lottery/new",
  CREATE_CUSTOMER: "customer/new",
  CUSTOMER_DETAIL: "customer/:id",

  COLLECTION_DETAIL: "collection/:id",
  LOTTERY_DETAIL: "room/:roomId",
  DEPOSITALHISTORYADMIN: "depositalhistory",
  CINEMA_DETAIL: "video/:title/:id/:userId",
  LOTERY: "lottery/:roomId/:userId",
  EDIT_USER: "edit/:id",
};
export default path;
